#!/usr/bin/env python3
"""The topic canon: 150 subjects worth studying, and how each maps to problems.

The bank tags only 36 topics, and those tags are coarse ("array", "design").
This is the syllabus instead. Each entry carries

    tags     - the bank's own tag names that imply this topic
    patterns - regexes over title + statement, for topics the tags cannot see
               (a "monotonic stack" problem is tagged "stack" at best)
    needs    - prerequisites, so a chapter can link backwards
    near     - sibling topics worth reading next
    covers   - smaller subjects folded into this chapter, which its article
               must still teach

Ordering is by how many problems in THIS bank actually use the topic, which is
computed rather than declared - see tools/topicmap.py. A topic with no problems
is kept and marked rare: it is still worth learning, and saying "nothing in the
bank uses it" is more useful than silence.
"""

import re

# category, slug, title, tags, patterns, needs, near, covers
CANON = [
 # --------------------------------------------------------------- Foundations
 ('Foundations', 'complexity-analysis', 'Time and Space Complexity',
  [], ['\\btime complexity\\b', '\\bO\\(n( log n)?\\)', '\\bbig-?o\\b'], [],
  ['amortized-analysis', 'recursion'], []),
 ('Foundations', 'amortized-analysis', 'Amortized Analysis',
  [],
  ['\\bamortized\\b', '\\bpotential method\\b', '\\bresiz(e|ing)\\b', '\\bdynamic array\\b', '\\bамортиз'],
  ['complexity-analysis'], ['stack'], ['Dynamic Arrays and Resizing']),
 ('Foundations', 'invariants', 'Loop Invariants and Correctness Proofs',
  [], ['\\binvariant\\b'], [], ['induction', 'binary-search'], []),
 ('Foundations', 'induction', 'Induction and Recursion Proofs',
  ['recursion'], ['\\binduction\\b'], [], ['invariants', 'recursion'], []),
 ('Foundations', 'recursion', 'Recursion and the Call Stack',
  ['recursion'], ['\\brecursi(on|ve)\\b', '\\bcall stack\\b'], [],
  ['backtracking', 'divide-and-conquer'], []),
 ('Foundations', 'divide-and-conquer', 'Divide and Conquer',
  [],
  ['\\bdivide and conquer\\b', '\\bmerge sort\\b', '\\bmaster theorem\\b', '\\brecurrence relation\\b'],
  ['recursion'], ['merge-sort'], ['The Master Theorem']),
 ('Foundations', 'randomized-algorithms', 'Randomised Algorithms',
  [],
  ['\\brandomi[sz]ed\\b', '\\bexpected time\\b', '\\brandom(ly)? (pick|choose|select)\\b', '\\bprobabilit\\w+\\b', '\\bexpected value\\b'],
  [], ['quickselect', 'reservoir-sampling'], ['Probability for Interviews']),
 # -------------------------------------------------------- Arrays and Strings
 ('Arrays and Strings', 'arrays', 'Arrays and Contiguous Memory',
  ['array'], ['\\barray\\b'], [], ['amortized-analysis', 'two-pointers'], []),
 ('Arrays and Strings', 'two-pointers', 'Two Pointers',
  ['two_pointers'], ['\\btwo pointers?\\b'], ['arrays'], ['sliding-window', 'fast-slow-pointers'],
  []),
 ('Arrays and Strings', 'fast-slow-pointers', 'Fast and Slow Pointers',
  [], ['\\bcycle detection\\b', '\\btortoise\\b', '\\bslow and fast\\b'], ['two-pointers'],
  ['linked-list', 'cycle-detection'], []),
 ('Arrays and Strings', 'sliding-window', 'Sliding Window',
  ['sliding_window'],
  ['\\bsliding window\\b', '\\bsubarray of (size|length) k\\b', '\\bcontiguous (subarray|window)\\b'],
  ['two-pointers'], ['prefix-sums', 'monotonic-deque'], []),
 ('Arrays and Strings', 'prefix-sums', 'Prefix Sums and Difference Arrays',
  ['prefix_sum'], ['\\bprefix sums?\\b', '\\brange sum\\b', '\\bdifference array\\b'], ['arrays'],
  ['sliding-window', 'fenwick-tree'], []),
 ('Arrays and Strings', 'in-place-rearrangement', 'In-place Rearrangement',
  [], ['\\bin[- ]place\\b', '\\bwithout extra space\\b', '\\bO\\(1\\) (extra )?space\\b'],
  ['arrays'], ['two-pointers', 'cyclic-sort'], []),
 ('Arrays and Strings', 'cyclic-sort', 'Cyclic Sort and Index-as-Hash',
  [], ['\\b1 to n\\b', '\\bmissing number\\b', '\\bduplicate number\\b'], ['arrays'],
  ['in-place-rearrangement', 'hash-tables'], []),
 ('Arrays and Strings', 'matrix-traversal', 'Matrix Traversal',
  ['matrix'], ['\\bmatrix\\b', '\\bgrid\\b', '\\bspiral\\b', '\\brotate the (image|matrix)\\b'],
  ['arrays'], ['flood-fill', 'grid-bfs'], []),
 ('Arrays and Strings', 'strings', 'Strings and Encoding',
  ['string'], ['\\bstring\\b', '\\bsubstring\\b', '\\brun[- ]length\\b', '\\bcompress\\w*\\b'],
  ['arrays'], ['string-matching', 'parsing'], ['Run-length and Simple Compression']),
 ('Arrays and Strings', 'string-matching', 'String Matching (KMP, Z, Rabin-Karp)',
  [],
  ['\\bKMP\\b', '\\bsubstring search\\b', '\\bpattern match\\w*\\b', '\\brabin[- ]karp\\b', '\\bZ[- ]algorithm\\b'],
  ['strings'], ['rolling-hash', 'trie'], []),
 ('Arrays and Strings', 'rolling-hash', 'Rolling Hash',
  [], ['\\brolling hash\\b', '\\bhash of (the )?substring\\b'], ['hash-tables', 'strings'],
  ['string-matching'], []),
 ('Arrays and Strings', 'palindromes', 'Palindromes',
  [], ['\\bpalindrom\\w+\\b'], ['strings'], ['two-pointers', 'dp-strings', 'manachers'], []),
 ('Arrays and Strings', 'manachers', "Manacher's Algorithm",
  [], ['\\bmanacher\\b', '\\blongest palindromic substring\\b'], ['palindromes'],
  ['string-matching'], []),
 ('Arrays and Strings', 'anagrams', 'Anagrams and Character Counting',
  [], ['\\banagram\\b', '\\bcharacter (count|frequency)\\b'], ['hash-tables', 'strings'],
  ['sliding-window'], []),
 ('Arrays and Strings', 'parsing', 'Parsing and Tokenising',
  ['parsing'], ['\\bpars(e|ing)\\b', '\\btoken(is|iz)e\\b', '\\bexpression\\b'], ['strings'],
  ['stack', 'recursive-descent'], []),
 ('Arrays and Strings', 'recursive-descent', 'Recursive-descent Evaluation',
  [], ['\\bevaluate the expression\\b', '\\bnested (expression|parenthes)\\w*'],
  ['parsing', 'recursion'], ['stack', 'parsing'], []),
 # ------------------------------------------------------------------- Hashing
 ('Hashing', 'hash-tables', 'Hash Tables',
  ['hash_table'],
  ['\\bhash (table|map|set)\\b', '\\bdictionary\\b', '\\bidempoten\\w+\\b', '\\bretry\\b', '\\bexactly once\\b', '\\bdeduplicat\\w+\\b'],
  ['arrays'], ['hash-functions'], ['Idempotency and Retries']),
 ('Hashing', 'hash-functions', 'Hash Functions',
  [], ['\\bhash function\\b', '\\bcollision\\b', '\\bopen addressing\\b', '\\bchaining\\b'],
  ['hash-tables'], ['rolling-hash'], ['Collision Resolution']),
 ('Hashing', 'frequency-counting', 'Frequency Counting',
  [],
  ['\\bfrequency\\b', '\\bcount(s|ing)? of each\\b', '\\bmost common\\b', '\\bgroup (by|the)\\b', '\\bbucket\\b'],
  ['hash-tables'], ['heap', 'counting-sort'], ['Grouping and Bucketing']),
 # ----------------------------------------------------- Sorting and Searching
 ('Sorting and Searching', 'sorting', 'Sorting: the Landscape',
  ['sorting'], ['\\bsort(ed|ing)?\\b', '\\blower bound\\b'], ['arrays'],
  ['merge-sort', 'quicksort'], ['The n log n Lower Bound']),
 ('Sorting and Searching', 'merge-sort', 'Merge Sort',
  [], ['\\bmerge sort\\b'], ['divide-and-conquer', 'sorting'], ['inversion-count'], []),
 ('Sorting and Searching', 'quicksort', 'Quicksort and Partitioning',
  [],
  ['\\bquick ?sort\\b', '\\bpartition(ing)? scheme\\b', '\\bdutch national flag\\b', '\\bsort colors\\b', '\\bthree[- ]way\\b'],
  ['sorting', 'randomized-algorithms'], ['quickselect'], ['Three-way Partitioning']),
 ('Sorting and Searching', 'quickselect', 'Quickselect and k-th Order Statistics',
  [], ['\\bkth (largest|smallest)\\b', '\\bquickselect\\b', '\\bmedian of\\b'], ['quicksort'],
  ['heap', 'median-maintenance'], []),
 ('Sorting and Searching', 'counting-sort', 'Counting and Radix Sort',
  [], ['\\bcounting sort\\b', '\\bradix sort\\b', '\\bbucket sort\\b'], ['sorting'], ['sorting'],
  ['Bucket Sort and Distribution']),
 ('Sorting and Searching', 'custom-comparators', 'Custom Comparators and Stability',
  [],
  ['\\bsort (them |the )?by\\b', '\\btie[- ]break\\w*', '\\bstable sort\\b', '\\bcomparator\\b'],
  ['sorting'], ['sorting', 'greedy-exchange'], []),
 ('Sorting and Searching', 'inversion-count', 'Counting Inversions',
  [], ['\\binversions?\\b', '\\bpairs? (i, ?j)\\b'], ['merge-sort'],
  ['fenwick-tree', 'merge-sort'], []),
 ('Sorting and Searching', 'binary-search', 'Binary Search',
  ['binary_search'],
  ['\\bbinary search\\b', '\\bsorted array\\b', '\\blower bound\\b', '\\bupper bound\\b', '\\bfirst (index|position) (where|such)\\b', '\\bbisect\\b'],
  ['invariants', 'arrays'], ['binary-search-on-answer'], ['Lower Bound, Upper Bound, bisect']),
 ('Sorting and Searching', 'binary-search-on-answer', 'Binary Search on the Answer',
  [],
  ['\\bminimi[sz]e the maximum\\b', '\\bmaximi[sz]e the minimum\\b', '\\bminimum (possible|such) (value|capacity|time|speed)\\b', '\\bsmallest (value|capacity|k) such that\\b', '\\bfeasib\\w+\\b', '\\bcan (we|you) (finish|complete|schedule)\\b'],
  ['binary-search'], ['greedy'], ['Monotone Predicates and Feasibility']),
 ('Sorting and Searching', 'ternary-search', 'Ternary Search and Unimodal Functions',
  [], ['\\bternary search\\b', '\\bunimodal\\b', '\\bconvex function\\b'], ['binary-search'],
  ['binary-search'], []),
 ('Sorting and Searching', 'search-rotated', 'Searching Rotated and Shifted Arrays',
  [], ['\\brotated (sorted )?array\\b', '\\bpivot\\b'], ['binary-search'], ['binary-search'], []),
 # --------------------------------------------------------- Linear Structures
 ('Linear Structures', 'stack', 'Stacks',
  ['stack'], ['\\bstack\\b', '\\bLIFO\\b'], ['arrays'], ['monotonic-stack', 'parsing'], []),
 ('Linear Structures', 'monotonic-stack', 'Monotonic Stack',
  [],
  ['\\bmonotonic stack\\b', '\\bnext greater\\b', '\\bprevious smaller\\b', '\\bstock span\\b', '\\blargest rectangle\\b', '\\bhistogram\\b', '\\bmaximal rectangle\\b'],
  ['stack'], ['monotonic-deque'], ['Largest Rectangle and Histogram Problems']),
 ('Linear Structures', 'queue', 'Queues and Ring Buffers',
  ['queue'], ['\\bqueue\\b', '\\bFIFO\\b', '\\bcircular buffer\\b'], ['arrays'],
  ['deque', 'monotonic-deque'], []),
 ('Linear Structures', 'deque', 'Deques',
  [], ['\\bdeque\\b', '\\bdouble[- ]ended\\b'], ['queue'], ['monotonic-deque', 'sliding-window'],
  []),
 ('Linear Structures', 'monotonic-deque', 'Monotonic Deque and Window Extremes',
  [], ['\\bsliding window (maximum|minimum)\\b', '\\bmonotonic (deque|queue)\\b'],
  ['deque', 'sliding-window'], ['sliding-window', 'monotonic-stack'], []),
 ('Linear Structures', 'linked-list', 'Linked Lists',
  ['linked_list'],
  ['\\blinked list\\b', '\\bnode\\.next\\b', '\\breverse (the )?(linked )?list\\b', '\\breorder list\\b'],
  ['arrays'], ['fast-slow-pointers'], ['Reversing and Reordering Lists']),
 ('Linear Structures', 'cycle-detection', 'Cycle Detection (Floyd, Brent)',
  [], ['\\bcycle\\b', '\\bloop in the (list|graph)\\b'], ['fast-slow-pointers'],
  ['linked-list', 'graphs'], []),
 ('Linear Structures', 'lru-cache', 'LRU and LFU Caches',
  [],
  ['\\bLRU\\b', '\\bLFU\\b', '\\bleast recently used\\b', '\\bcache\\b', '\\beviction\\b', '\\bTTL\\b'],
  ['hash-tables', 'linked-list'], ['design-data-structure'], ['Caching Strategies']),
 # --------------------------------------------------------------------- Trees
 ('Trees', 'trees', 'Trees: Vocabulary and Shapes',
  ['tree'],
  ['\\bbinary tree\\b', '\\btree\\b', '\\broot\\b', '\\bn[- ]ary tree\\b', '\\bchildren\\b', '\\bforest\\b'],
  ['recursion'], ['tree-traversal', 'bst'], ['N-ary Trees and Forests']),
 ('Trees', 'tree-traversal', 'Tree Traversals',
  [], ['\\b(in|pre|post)order\\b', '\\blevel[- ]order\\b', '\\btraversal\\b'], ['trees'],
  ['bfs', 'dfs', 'morris-traversal'], []),
 ('Trees', 'morris-traversal', 'Morris Traversal (O(1) space)',
  [], ['\\bmorris\\b', '\\bconstant space traversal\\b'], ['tree-traversal'], ['tree-traversal'],
  []),
 ('Trees', 'bst', 'Binary Search Trees',
  [], ['\\bbinary search tree\\b', '\\bBST\\b'], ['trees', 'binary-search'],
  ['balanced-bst', 'tree-traversal'], []),
 ('Trees', 'balanced-bst', 'Balanced Trees: AVL and Red-Black',
  [],
  ['\\bAVL\\b', '\\bred[- ]black\\b', '\\bbalanced (binary )?tree\\b', '\\brotation\\b', '\\btreap\\b', '\\brandomi[sz]ed (binary )?search tree\\b'],
  ['bst'], ['bst'], ['Treaps and Randomised BSTs']),
 ('Trees', 'tree-dp', 'Tree DP and Rerooting',
  [], ['\\bsubtree\\b.*\\b(sum|count|max)\\b', '\\brerooting\\b'],
  ['trees', 'dynamic-programming'], ['dfs', 'dynamic-programming'], []),
 ('Trees', 'lca', 'Lowest Common Ancestor',
  [], ['\\blowest common ancestor\\b', '\\bLCA\\b'], ['trees'],
  ['binary-lifting', 'tree-traversal'], []),
 ('Trees', 'binary-lifting', 'Binary Lifting',
  [], ['\\bbinary lifting\\b', '\\bkth ancestor\\b', '\\bjump pointers?\\b'], ['lca'],
  ['lca', 'sparse-table'], []),
 ('Trees', 'trie', 'Tries (Prefix Trees)',
  ['trie'],
  ['\\btrie\\b', '\\bprefix tree\\b', '\\bautocomplete\\b', '\\baho[- ]corasick\\b', '\\bmultiple patterns\\b'],
  ['trees', 'strings'], ['string-matching'], ['Aho-Corasick Multi-pattern Matching']),
 ('Trees', 'serialize-tree', 'Serialising and Rebuilding Trees',
  [],
  ['\\bserial(i[sz]e|isation|ization)\\b', '\\breconstruct the tree\\b', '\\bbuild the tree from\\b'],
  ['tree-traversal'], ['tree-traversal', 'design-data-structure'], []),
 # --------------------------------------------------------------------- Heaps
 ('Heaps', 'heap', 'Binary Heaps and Priority Queues',
  ['heap'],
  ['\\bheap\\b', '\\bpriority queue\\b', '\\bheapsort\\b', '\\bheapify\\b', '\\bbuild[- ]heap\\b'],
  ['trees', 'arrays'], ['top-k'], ['Heapsort and Heapify']),
 ('Heaps', 'top-k', 'Top-k Selection',
  [], ['\\btop[- ]?k\\b', '\\bk (most|largest|smallest|closest|frequent)\\b'], ['heap'],
  ['quickselect', 'frequency-counting'], []),
 ('Heaps', 'median-maintenance', 'Two Heaps and Running Medians',
  [], ['\\bmedian\\b.*\\bstream\\b', '\\brunning median\\b', '\\btwo heaps\\b'], ['heap'],
  ['streaming', 'heap'], []),
 ('Heaps', 'k-way-merge', 'k-way Merge',
  [], ['\\bmerge k\\b', '\\bk sorted (lists|arrays)\\b'], ['heap'], ['merge-sort', 'heap'], []),
 # -------------------------------------------------------------------- Graphs
 ('Graphs', 'graphs', 'Graphs: Representation',
  ['graph'], ['\\bgraph\\b', '\\badjacency\\b', '\\bedges?\\b', '\\bnodes? and edges\\b'],
  ['arrays', 'hash-tables'], ['bfs', 'dfs', 'graph-modelling'], []),
 ('Graphs', 'graph-modelling', 'Modelling a Problem as a Graph',
  [], ['\\bconvert\\b.*\\bgraph\\b', '\\bdependenc\\w+\\b', '\\breachab\\w+\\b'], ['graphs'],
  ['topological-sort', 'bfs'], []),
 ('Graphs', 'bfs', 'Breadth-first Search',
  ['breadth_first_search'],
  ['\\bBFS\\b', '\\bbreadth[- ]first\\b', '\\bshortest (path|number of steps)\\b.*\\bunweighted\\b'],
  ['queue', 'graphs'], ['grid-bfs', 'meet-in-the-middle', 'shortest-path'], []),
 ('Graphs', 'dfs', 'Depth-first Search',
  ['depth_first_search'], ['\\bDFS\\b', '\\bdepth[- ]first\\b'], ['recursion', 'graphs'],
  ['backtracking', 'cycle-detection-graph'], []),
 ('Graphs', 'grid-bfs', 'BFS and DFS on Grids',
  [],
  ['\\bgrid\\b.*\\b(shortest|island|region)\\b', '\\b4[- ]direction\\w*', '\\bneighbou?ring cells?\\b'],
  ['bfs', 'matrix-traversal'], ['flood-fill', 'multi-source-bfs'], []),
 ('Graphs', 'flood-fill', 'Flood Fill and Connected Components',
  [], ['\\bflood fill\\b', '\\bislands?\\b', '\\bconnected (component|region)s?\\b'],
  ['dfs', 'grid-bfs'], ['union-find', 'grid-bfs'], []),
 ('Graphs', 'multi-source-bfs', 'Multi-source BFS',
  [], ['\\bmulti[- ]source\\b', '\\ball .* simultaneously\\b', '\\brot(ting|ten)\\b'], ['bfs'],
  ['bfs', 'grid-bfs'], []),
 ('Graphs', 'topological-sort', 'Topological Sort',
  ['topological_sort'],
  ['\\btopological\\b', '\\bprerequisite\\b', '\\bdependency order\\b', '\\bbuild order\\b', '\\blongest path\\b', '\\bDAG\\b'],
  ['dfs', 'graphs'], ['cycle-detection-graph'], ['DP on a DAG']),
 ('Graphs', 'cycle-detection-graph', 'Cycle Detection in Graphs',
  [], ['\\bcycle\\b.*\\bgraph\\b', '\\bdetect (a )?cycle\\b'], ['dfs'],
  ['topological-sort', 'union-find'], []),
 ('Graphs', 'shortest-path', 'Shortest Paths: the Map',
  ['shortest_path'], ['\\bshortest path\\b', '\\bminimum (cost|time) to (reach|travel)\\b'],
  ['graphs'], ['dijkstra', 'bellman-ford', 'floyd-warshall'], []),
 ('Graphs', 'dijkstra', "Dijkstra's Algorithm",
  [],
  ['\\bdijkstra\\b', '\\bshortest path\\b.*\\bweight\\w*\\b', '\\bA\\*\\b', '\\bheuristic\\b'],
  ['heap', 'shortest-path'], ['bellman-ford'], ['A* and Heuristic Search']),
 ('Graphs', 'bellman-ford', 'Bellman-Ford and Negative Edges',
  [], ['\\bbellman[- ]ford\\b', '\\bnegative (edge|weight|cycle)\\b'], ['shortest-path'],
  ['dijkstra', 'floyd-warshall'], []),
 ('Graphs', 'floyd-warshall', 'Floyd-Warshall (All Pairs)',
  [], ['\\bfloyd[- ]warshall\\b', '\\ball pairs\\b'], ['shortest-path', 'dynamic-programming'],
  ['dijkstra'], []),
 ('Graphs', 'minimum-spanning-tree', 'Minimum Spanning Trees (Kruskal, Prim)',
  [],
  ['\\bspanning tree\\b', '\\bkruskal\\b', '\\bprim\\b', '\\bconnect all\\b.*\\bminimum cost\\b'],
  ['union-find', 'heap'], ['union-find', 'greedy'], []),
 ('Graphs', 'union-find', 'Union-Find (Disjoint Set Union)',
  ['union_find'],
  ['\\bunion[- ]find\\b', '\\bdisjoint set\\b', '\\bDSU\\b', '\\bmerge (the )?(groups|sets|accounts)\\b'],
  ['arrays'], ['minimum-spanning-tree', 'flood-fill'], []),
 ('Graphs', 'bipartite', 'Bipartite Graphs and 2-colouring',
  [],
  ['\\bbipartite\\b', '\\btwo colou?rs?\\b', '\\bpossible bipartition\\b', '\\bcolou?ring\\b', '\\bk colou?rs\\b'],
  ['bfs', 'graphs'], ['bfs'], ['Graph Colouring']),
 ('Graphs', 'eulerian-path', 'Eulerian Paths and Circuits',
  [],
  ['\\beuler\\w*\\b', '\\buse every edge\\b', '\\bitinerary\\b', '\\bhierholzer\\b', '\\breconstruct itinerary\\b'],
  ['graphs'], ['graphs'], ["Hierholzer's Algorithm"]),
 ('Graphs', 'strongly-connected', 'Strongly Connected Components',
  [],
  ['\\bstrongly connected\\b', '\\btarjan\\b', '\\bkosaraju\\b', '\\bSCC\\b', '\\bcondensation\\b', '\\bcomponent graph\\b'],
  ['dfs'], ['dfs'], ['Condensation and Component Graphs']),
 ('Graphs', 'bridges-articulation', 'Bridges and Articulation Points',
  [], ['\\bbridge\\b', '\\barticulation\\b', '\\bcritical connection\\b'], ['dfs'],
  ['strongly-connected'], []),
 ('Graphs', 'max-flow', 'Max Flow and Min Cut',
  [],
  ['\\bmax(imum)? flow\\b', '\\bmin(imum)? cut\\b', '\\bford[- ]fulkerson\\b', '\\bedmonds[- ]karp\\b', '\\bmatching\\b', '\\bassign(ment)?\\b.*\\bone[- ]to[- ]one\\b', '\\bhungarian\\b'],
  ['bfs', 'graphs'], [], ['Bipartite Matching']),
 # ------------------------------------------------------- Dynamic Programming
 ('Dynamic Programming', 'dynamic-programming', 'Dynamic Programming: the Method',
  ['dynamic_programming'],
  ['\\bdynamic programming\\b', '\\bDP\\b', '\\bmemoi[sz]\\w+\\b', '\\bconvex hull trick\\b', '\\bdivide and conquer optimi[sz]ation\\b', '\\bmonotonic\\b.*\\bDP\\b'],
  ['recursion'], ['dp-1d', 'dp-2d', 'memoization'], ['DP Optimisation (monotonic, convex hull)']),
 ('Dynamic Programming', 'memoization', 'Memoisation vs Tabulation',
  ['dynamic_programming'], ['\\bmemoi[sz]\\w+\\b', '\\btop[- ]down\\b', '\\bbottom[- ]up\\b'], ['dynamic-programming'],
  ['dynamic-programming', 'state-design'], []),
 ('Dynamic Programming', 'state-design', 'Designing the State',
  ['dynamic_programming'], ['\\bstate\\b.*\\btransition\\b'], ['dynamic-programming'], ['dp-1d', 'dp-bitmask'], []),
 ('Dynamic Programming', 'dp-1d', 'One-dimensional DP',
  [], ['\\bhouse robber\\b', '\\bclimb\\w* stairs\\b', '\\bmax(imum)? (sum )?subarray\\b'],
  ['dynamic-programming'], ['kadane', 'dp-2d'], []),
 ('Dynamic Programming', 'kadane', "Kadane's Algorithm",
  [],
  ['\\bkadane\\b', '\\bmaximum subarray sum\\b', '\\bcontiguous subarray\\b.*\\blargest sum\\b'],
  ['dp-1d'], ['dp-1d', 'prefix-sums'], []),
 ('Dynamic Programming', 'dp-2d', 'Two-dimensional DP and Grids',
  [], ['\\bunique paths\\b', '\\bminimum path sum\\b', '\\bgrid\\b.*\\bDP\\b'],
  ['dynamic-programming'], ['dp-strings', 'matrix-traversal'], []),
 ('Dynamic Programming', 'dp-strings', 'DP on Strings (Edit Distance, LCS)',
  [],
  ['\\bedit distance\\b', '\\blongest common subsequence\\b', '\\bLCS\\b', '\\bsubsequence\\b'],
  ['dp-2d', 'strings'], ['lis', 'palindromes'], []),
 ('Dynamic Programming', 'lis', 'Longest Increasing Subsequence',
  [],
  ['\\blongest increasing subsequence\\b', '\\bLIS\\b', '\\bincreasing subsequence\\b', '\\bpatience\\b', '\\bpile\\b'],
  ['dp-1d', 'binary-search'], ['dp-1d'], ['Patience Sorting and the n log n LIS']),
 ('Dynamic Programming', 'knapsack', 'Knapsack',
  [], ['\\bknapsack\\b', '\\bcapacity\\b.*\\bmaximi[sz]e\\b', '\\bsubset sum\\b'],
  ['dynamic-programming'], ['unbounded-knapsack', 'partition-dp'], []),
 ('Dynamic Programming', 'unbounded-knapsack', 'Unbounded Knapsack and Coin Change',
  [], ['\\bcoin change\\b', '\\bunbounded\\b', '\\bunlimited (supply|number)\\b'], ['knapsack'],
  ['knapsack', 'counting-dp'], []),
 ('Dynamic Programming', 'partition-dp', 'Partition and Interval DP',
  [], ['\\bpartition\\b', '\\bburst balloons\\b', '\\bmatrix chain\\b', '\\bsplit the array\\b'],
  ['dynamic-programming'], ['dp-2d', 'knapsack'], []),
 ('Dynamic Programming', 'counting-dp', 'Counting with DP',
  [], ['\\bnumber of ways\\b', '\\bcount the (number of )?(ways|paths|combinations)\\b'],
  ['dynamic-programming', 'combinatorics'], ['combinatorics', 'dp-1d'], []),
 ('Dynamic Programming', 'dp-bitmask', 'Bitmask DP',
  [], ['\\bbitmask\\b', '\\bsubsets? of\\b.*\\bDP\\b', '\\btravelling salesman\\b', '\\bTSP\\b'],
  ['bit-manipulation', 'dynamic-programming'], ['bit-manipulation', 'state-design'], []),
 ('Dynamic Programming', 'digit-dp', 'Digit DP',
  [], ['\\bdigit DP\\b', '\\bnumbers? (between|from) \\d+ (to|and)\\b.*\\bcount\\b'],
  ['dynamic-programming'], ['counting-dp', 'math'], []),
 ('Dynamic Programming', 'game-dp', 'Game Theory DP (Minimax, Nim)',
  [],
  ['\\bgame\\b.*\\boptimal(ly)?\\b', '\\bminimax\\b', '\\bnim\\b', '\\btwo players?\\b', '\\balpha[- ]beta\\b', '\\bgrundy\\b', '\\bsprague\\b', '\\bwinning (position|strategy)\\b'],
  ['dynamic-programming'], [], ['Minimax and Alpha-Beta', 'Combinatorial Game Theory']),
 # -------------------------------------------------------------------- Greedy
 ('Greedy', 'greedy', 'Greedy Algorithms',
  ['greedy'], ['\\bgreedy\\b', '\\bminimum number of\\b', '\\bmaximi[sz]e the number of\\b'],
  ['sorting'], ['greedy-exchange', 'intervals'], []),
 ('Greedy', 'greedy-exchange', 'Proving Greedy: Exchange Arguments',
  ['greedy'], ['\\bexchange argument\\b', '\\boptimal substructure\\b', '\\bmatroid\\b'],
  ['greedy', 'induction'], ['greedy'], ['Matroids and When Greedy Works']),
 ('Greedy', 'intervals', 'Interval Problems',
  ['intervals'],
  ['\\bintervals?\\b', '\\bmerge overlapping\\b', '\\bmeeting rooms?\\b', '\\bstart and end times?\\b'],
  ['sorting', 'greedy'], ['sweep-line', 'scheduling'], []),
 ('Greedy', 'sweep-line', 'Sweep Line and Event Processing',
  [],
  ['\\bsweep\\b', '\\bevents?\\b.*\\b(sorted|order)\\b', '\\bskyline\\b', '\\brectangles?\\b.*\\barea\\b', '\\bclosest pair\\b', '\\bsegment intersection\\b'],
  ['intervals', 'sorting'], ['intervals', 'heap'], ['Sweep Line in Geometry']),
 ('Greedy', 'scheduling', 'Scheduling and Deadlines',
  [],
  ['\\bdeadline\\b', '\\bschedul\\w+\\b', '\\bcooldown\\b', '\\btask assignment\\b', '\\bmeeting rooms?\\b', '\\btask(s)? (with )?cooldown\\b'],
  ['greedy', 'heap'], ['greedy'], ['Scheduling with a Heap']),
 ('Greedy', 'huffman', 'Huffman Coding',
  [], ['\\bhuffman\\b', '\\bprefix code\\b', '\\bencode\\b.*\\bfrequency\\b'], ['heap', 'greedy'],
  ['greedy', 'trees'], []),
 # ---------------------------------------------------- Search and Enumeration
 ('Search and Enumeration', 'backtracking', 'Backtracking',
  ['backtracking'],
  ['\\bbacktrack\\w*\\b', '\\ball possible\\b', '\\bgenerate all\\b', '\\bpermutations?\\b', '\\bcombinations?\\b', '\\biterative deepening\\b', '\\bIDA\\*\\b'],
  ['recursion', 'dfs'], ['permutations', 'pruning'], ['Iterative Deepening']),
 ('Search and Enumeration', 'permutations', 'Permutations and Combinations (generation)',
  [], ['\\bpermutations?\\b', '\\bcombinations?\\b', '\\bsubsets?\\b', '\\bpower set\\b'],
  ['backtracking'], ['combinatorics', 'backtracking'], []),
 ('Search and Enumeration', 'pruning', 'Pruning and Constraint Propagation',
  [], ['\\bprun\\w+\\b', '\\bconstraint\\b', '\\bsudoku\\b', '\\bn[- ]queens\\b'],
  ['backtracking'], ['backtracking', 'bipartite'], []),
 ('Search and Enumeration', 'meet-in-the-middle', 'Meet in the Middle',
  [],
  ['\\bmeet in the middle\\b', '\\bsplit (the )?(array|set) in half\\b', '\\bbidirectional\\b'],
  ['backtracking'], ['subsets'], ['Bidirectional Search']),
 ('Search and Enumeration', 'subsets', 'Subset Enumeration',
  [], ['\\bsubsets?\\b', '\\b2\\^n\\b'], ['bit-manipulation', 'backtracking'],
  ['dp-bitmask', 'permutations'], []),
 # --------------------------------------------------------------- Mathematics
 ('Mathematics', 'math', 'Maths for Interviews',
  ['math'], ['\\bmath\\w*\\b', '\\bmodulo\\b', '\\bdivisib\\w+\\b'], [],
  ['number-theory', 'combinatorics'], []),
 ('Mathematics', 'number-theory', 'Number Theory Basics',
  [], ['\\bgcd\\b', '\\blcm\\b', '\\bprime\\b', '\\bfactor\\w*\\b'], ['math'],
  ['primes', 'modular-arithmetic'], []),
 ('Mathematics', 'primes', 'Primes and the Sieve',
  [],
  ['\\bprime\\b', '\\bsieve\\b', '\\beratosthenes\\b', '\\bdivisors?\\b', '\\bfactori[sz]ation\\b', '\\bprime factors?\\b'],
  ['number-theory'], ['number-theory'], ['Factorisation and Divisors']),
 ('Mathematics', 'modular-arithmetic', 'Modular Arithmetic',
  [],
  ['\\bmodulo 10\\^9\\b', '\\bmod(ulo|ular)?\\b', '\\b1000000007\\b', '\\bmodular inverse\\b', '\\bfermat\\b'],
  ['math'], ['fast-exponentiation'], ['Modular Inverse and Fermat']),
 ('Mathematics', 'fast-exponentiation', 'Fast Exponentiation',
  [], ['\\bfast (exponentiation|power)\\b', '\\bpow\\(.*mod\\b', '\\bbinary exponentiation\\b'],
  ['modular-arithmetic'], ['matrix-exponentiation'], []),
 ('Mathematics', 'matrix-exponentiation', 'Matrix Exponentiation',
  [], ['\\bmatrix exponentiation\\b', '\\bfibonacci\\b.*\\blarge n\\b'], ['fast-exponentiation'],
  ['fast-exponentiation', 'dynamic-programming'], []),
 ('Mathematics', 'combinatorics', 'Combinatorics and Counting',
  ['combinatorics'],
  ['\\bcombinatorics\\b', '\\bbinomial\\b', '\\bfactorial\\b', '\\bhow many ways\\b', '\\bpigeonhole\\b'],
  ['math'], ['counting-dp', 'inclusion-exclusion'], ['Pigeonhole and Counting Arguments']),
 ('Mathematics', 'inclusion-exclusion', 'Inclusion-Exclusion',
  [], ['\\binclusion[- ]exclusion\\b', '\\bat least one\\b.*\\bcount\\b'], ['combinatorics'],
  ['combinatorics'], []),
 ('Mathematics', 'geometry', 'Computational Geometry Basics',
  ['geometry'],
  ['\\bgeometr\\w+\\b', '\\bpoints? (on|in) (the |a )?plane\\b', '\\bcoordinates?\\b'], ['math'],
  ['convex-hull', 'sweep-line'], []),
 ('Mathematics', 'convex-hull', 'Convex Hull',
  [], ['\\bconvex hull\\b', '\\bgraham scan\\b', "\\bandrew'?s monotone\\b"],
  ['geometry', 'sorting'], ['geometry'], []),
 ('Mathematics', 'numerical-stability', 'Floating Point and Precision',
  [], ['\\bfloating point\\b', '\\bprecision\\b', '\\bepsilon\\b', '\\brounding\\b'], ['math'],
  ['math'], []),
 ('Mathematics', 'big-integers', 'Big Integers and Overflow',
  [], ['\\boverflow\\b', '\\b64[- ]bit\\b', '\\blong long\\b', '\\bbig integer\\b'], ['math'],
  ['modular-arithmetic', 'numerical-stability'], []),
 ('Mathematics', 'base-conversion', 'Number Bases and Conversion',
  [],
  ['\\bbase[- ]?\\d+\\b', '\\bbinary representation\\b', '\\bhexadecimal\\b', '\\bconvert.*\\bbase\\b'],
  ['math'], ['bit-manipulation'], []),
 # ---------------------------------------------------------- Bit Manipulation
 ('Bit Manipulation', 'bit-manipulation', 'Bit Manipulation',
  ['bit_manipulation'],
  ['\\bbitwise\\b', '\\bXOR\\b', '\\bbitmask\\b', '\\bbit mask\\b', '\\b(left|right) shift\\b', '\\bcount (the )?(set )?bits\\b', '\\bpopcount\\b', '\\blowest set bit\\b', '\\bn & \\(n - 1\\)\\b'],
  [], ['subsets'], ['Bit Tricks Worth Memorising']),
 ('Bit Manipulation', 'xor-tricks', 'XOR Properties',
  [], ['\\bXOR\\b', '\\bsingle number\\b', '\\bappears (once|twice)\\b'], ['bit-manipulation'],
  ['bit-manipulation', 'prefix-sums'], []),
 # ------------------------------------------------------- Advanced Structures
 ('Advanced Structures', 'fenwick-tree', 'Fenwick Tree (BIT)',
  [], ['\\bfenwick\\b', '\\bbinary indexed tree\\b', '\\bBIT\\b.*\\bprefix\\b'], ['prefix-sums'],
  ['segment-tree', 'inversion-count'], []),
 ('Advanced Structures', 'segment-tree', 'Segment Trees',
  ['segment_tree'], ['\\bsegment tree\\b', '\\brange (query|update)\\b'], ['trees', 'recursion'],
  ['lazy-propagation', 'fenwick-tree'], []),
 ('Advanced Structures', 'lazy-propagation', 'Lazy Propagation',
  [], ['\\blazy propagation\\b', '\\brange update\\b'], ['segment-tree'], ['segment-tree'], []),
 ('Advanced Structures', 'sparse-table', 'Sparse Tables and Static RMQ',
  [], ['\\bsparse table\\b', '\\brange minimum query\\b', '\\bRMQ\\b'], ['binary-lifting'],
  ['segment-tree', 'binary-lifting'], []),
 ('Advanced Structures', 'sqrt-decomposition', "Sqrt Decomposition and Mo's Algorithm",
  [],
  ['\\bsqrt decomposition\\b', "\\bmo'?s algorithm\\b", '\\bblock size\\b', '\\boffline\\b.*\\bqueries\\b', '\\bprocess the queries in order\\b'],
  ['arrays'], ['segment-tree'], ['Offline Query Processing']),
 ('Advanced Structures', 'ordered-set', 'Ordered Sets and Balanced-tree Maps',
  [],
  ['\\bordered (set|map)\\b', '\\bsorted container\\b', '\\bTreeMap\\b', '\\bSortedList\\b', '\\bskip list\\b'],
  ['balanced-bst'], ['balanced-bst', 'binary-search'], ['Skip Lists']),
 ('Advanced Structures', 'bloom-filter', 'Bloom Filters',
  [], ['\\bbloom filter\\b', '\\bfalse positive\\b'], ['hash-functions'],
  ['hash-functions', 'streaming'], []),
 ('Advanced Structures', 'suffix-structures', 'Suffix Arrays and Automata',
  [], ['\\bsuffix (array|tree|automaton)\\b'], ['strings', 'sorting'],
  ['string-matching', 'trie'], []),
 ('Advanced Structures', 'persistent-structures', 'Persistent Data Structures',
  [],
  ['\\bpersistent\\b', '\\bversion\\w*\\b.*\\bhistory\\b', '\\bsnapshot\\b', '\\bversion\\w*\\b', '\\bhistory of\\b'],
  ['trees'], ['design-data-structure', 'segment-tree'], ['Versioning and Snapshots']),
 # -------------------------------------------------------- Design and Systems
 ('Design and Systems', 'design-data-structure', 'Designing a Data Structure',
  ['design'],
  ['\\bdesign (a|an|the)\\b', '\\bimplement (a|an|the)\\b.*\\bclass\\b', '\\bsupports? the following operations\\b', '\\biterator\\b', '\\bgenerator\\b', '\\blazy evaluation\\b', '\\bAPI\\b', '\\bmethods?\\b.*\\bsupport\\b', '\\bpaginat\\w+\\b', '\\bcursor\\b', '\\bpage (size|token)\\b'],
  ['hash-tables', 'linked-list'], ['lru-cache'],
  ['Iterators and Generators', 'Designing an API Surface', 'Pagination and Cursors']),
 ('Design and Systems', 'simulation', 'Simulation Problems',
  ['simulation'],
  ['\\bsimulat\\w+\\b', '\\bstep by step\\b', '\\bprocess the (events|operations) in order\\b', '\\bevent log\\b', '\\breplay\\b', '\\baudit\\b', '\\bledger\\b'],
  ['arrays'], ['state-machines', 'design-data-structure'], ['Event Logs and Replay']),
 ('Design and Systems', 'state-machines', 'State Machines',
  [], ['\\bstate machine\\b', '\\bstates? and transitions?\\b', '\\bvalid (number|state)\\b'],
  ['simulation'], ['simulation', 'parsing'], []),
 ('Design and Systems', 'streaming', 'Streaming and Online Algorithms',
  [], ['\\bstream\\w*\\b', '\\bonline\\b', '\\bone pass\\b'], ['heap'],
  ['reservoir-sampling', 'median-maintenance'], []),
 ('Design and Systems', 'reservoir-sampling', 'Reservoir Sampling',
  [], ['\\breservoir\\b', '\\brandom(ly)? (pick|sample)\\b.*\\bstream\\b'],
  ['randomized-algorithms', 'streaming'], ['streaming', 'randomized-algorithms'], []),
 ('Design and Systems', 'rate-limiting', 'Rate Limiting and Token Buckets',
  [],
  ['\\brate limit\\w*\\b', '\\btoken bucket\\b', '\\bthrottl\\w+\\b', '\\brequests? per second\\b'],
  ['queue', 'design-data-structure'], ['design-data-structure', 'simulation'], []),
 ('Design and Systems', 'concurrency', 'Concurrency Primitives',
  ['concurrency'],
  ['\\bconcurren\\w+\\b', '\\bthread\\b', '\\block\\b', '\\bmutex\\b', '\\bsemaphore\\b'], [],
  ['producer-consumer', 'deadlock'], []),
 ('Design and Systems', 'producer-consumer', 'Producer-Consumer and Bounded Buffers',
  [], ['\\bproducer\\b', '\\bconsumer\\b', '\\bbounded buffer\\b'], ['concurrency'],
  ['concurrency'], []),
 ('Design and Systems', 'deadlock', 'Deadlock and Livelock',
  [], ['\\bdeadlock\\b', '\\bstarvation\\b'], ['concurrency'], ['concurrency'], []),
 # -------------------------------------------------------------- Data and SQL
 ('Data and SQL', 'sql-basics', 'SQL: SELECT, WHERE, ORDER BY',
  ['database'], ['\\bSELECT\\b', '\\bWHERE\\b', '\\bORDER BY\\b', '\\bSQL\\b'], [],
  ['sql-joins', 'sql-aggregation'], []),
 ('Data and SQL', 'sql-joins', 'SQL Joins',
  ['database'], ['\\bJOIN\\b', '\\bLEFT JOIN\\b', '\\bself[- ]join\\b'], ['sql-basics'],
  ['sql-aggregation', 'sql-window'], []),
 ('Data and SQL', 'sql-aggregation', 'GROUP BY and Aggregation',
  ['database'],
  ['\\bGROUP BY\\b', '\\bHAVING\\b', '\\bCOUNT\\(|SUM\\(|AVG\\(', '\\baverage\\b', '\\bpandas\\b', '\\bDataFrame\\b', '\\bgroupby\\b'],
  ['sql-basics'], ['sql-window', 'sql-joins'], ['DataFrames (pandas)']),
 ('Data and SQL', 'sql-window', 'Window Functions',
  [],
  ['\\bwindow function\\b', '\\bROW_NUMBER\\b', '\\bRANK\\b', '\\bOVER \\(|PARTITION BY\\b', '\\bnth (highest|largest)\\b'],
  ['sql-aggregation'], ['sql-aggregation'], []),
 ('Data and SQL', 'sql-subqueries', 'Subqueries and CTEs',
  [], ['\\bWITH\\b.*\\bAS \\(', '\\bsubquer\\w+\\b', '\\bCTE\\b', '\\brecursive query\\b'],
  ['sql-basics'], ['sql-joins', 'sql-window'], []),
 # ----------------------------------------------------------- Interview Craft
 ('Interview Craft', 'problem-decomposition', 'Reading a Problem and Decomposing It',
  [], [], [], ['pattern-recognition', 'edge-cases'], []),
 ('Interview Craft', 'pattern-recognition', 'Recognising the Pattern from the Statement',
  [], [], ['problem-decomposition'], ['binary-search-on-answer', 'sliding-window'], []),
 ('Interview Craft', 'edge-cases', 'Edge Cases and Defensive Thinking',
  [], ['\\bedge case\\b', '\\bempty (array|string|input)\\b'], [],
  ['testing-your-code', 'invariants'], []),
 ('Interview Craft', 'testing-your-code', 'Testing Your Own Solution',
  [], [], ['edge-cases'], ['edge-cases', 'complexity-analysis'], []),
 ('Interview Craft', 'debugging', 'Debugging Under Time Pressure',
  [], ['\\bdebug\\w*\\b', '\\bfix the bug\\b'], [], ['testing-your-code'], []),
 ('Interview Craft', 'optimisation-path', 'From Brute Force to Optimal',
  [], ['\\bbrute force\\b', '\\boptimi[sz]e\\b'], ['complexity-analysis'],
  ['pattern-recognition'], []),
 ('Interview Craft', 'communication', 'Explaining Your Approach Out Loud',
  [], [], [], ['problem-decomposition'], []),
]


def by_slug():
    return {c[1]: dict(zip(("category", "slug", "title", "tags", "patterns",
                            "needs", "near", "covers"), c)) for c in CANON}


def check():
    slugs = [c[1] for c in CANON]
    assert len(slugs) == len(set(slugs)), "duplicate slug"
    known = set(slugs)
    for c in CANON:
        for ref in c[5] + c[6]:
            assert ref in known, "%s points at unknown topic %s" % (c[1], ref)
        for pat in c[4]:
            re.compile(pat, re.I)
    return len(CANON)


if __name__ == "__main__":
    import collections
    print("%d topics in %d categories" % (check(), len({c[0] for c in CANON})))
    for cat, n in collections.Counter(c[0] for c in CANON).most_common():
        print("  %-24s %d" % (cat, n))
