# Approach: BFS over one-letter-change neighbours generated by wildcard patterns.
from typing import List, Optional, Any
from collections import deque


def ladderLength(beginWord: str, endWord: str, wordList: List[str]) -> int:
    words = set(wordList)
    if endWord not in words:
        return 0
    L = len(beginWord)
    q = deque([(beginWord, 1)])
    words.discard(beginWord)
    while q:
        word, steps = q.popleft()
        if word == endWord:
            return steps
        for i in range(L):
            head, tail = word[:i], word[i + 1:]
            for c in "abcdefghijklmnopqrstuvwxyz":
                if c == word[i]:
                    continue
                cand = head + c + tail
                if cand in words:
                    words.discard(cand)
                    q.append((cand, steps + 1))
    return 0
