"""The study space: the topic canon, its articles, and each topic's problems.

topics/INDEX.json is generated by tools/topicmap.py from the bank plus
tools/canon.py; the articles are Markdown under topics/articles/<slug>.md.
Both are read from disk on demand and cached by mtime, so editing an article
shows up on the next request without restarting the server.

Nothing here writes to the bank. Study state (read / notes) lives in the
progress database next to the rest of the user's data.
"""

from __future__ import annotations

import json
import os
import re

import mdlite

HERE = os.path.dirname(os.path.abspath(__file__))
INDEX_PATH = os.path.join(HERE, "topics", "INDEX.json")
ARTICLE_DIR = os.path.join(HERE, "topics", "articles")

_cache: dict = {"index": None, "mtime": None, "articles": {}}


# --------------------------------------------------------------------- index
def index() -> dict:
    try:
        m = os.path.getmtime(INDEX_PATH)
    except OSError:
        return {"problems": 0, "topics": [], "byProblem": {}}
    if _cache["index"] is None or _cache["mtime"] != m:
        with open(INDEX_PATH) as fh:
            data = json.load(fh)
        data["bySlug"] = {t["slug"]: t for t in data["topics"]}
        _cache["index"], _cache["mtime"] = data, m
    return _cache["index"]


def topics_for(pid: str) -> list[dict]:
    """The topic links to show under a problem statement."""
    idx = index()
    out = []
    for slug in idx.get("byProblem", {}).get(pid, []):
        t = idx["bySlug"].get(slug)
        if t:
            out.append({"slug": slug, "title": t["title"], "count": t["count"]})
    return out


# ------------------------------------------------------------------ articles
def article_path(slug: str) -> str:
    return os.path.join(ARTICLE_DIR, "%s.md" % slug)


def _summary(src: str) -> str:
    for line in src.split("\n"):
        s = line.strip()
        if s.startswith(">"):
            return re.sub(r"[*`]", "", s.lstrip("> ").strip())
    for para in re.split(r"\n\s*\n", src):
        p = para.strip()
        if p and not p.startswith("#"):
            return re.sub(r"[*`]", "", p.split("\n")[0])[:240]
    return ""


def article(slug: str) -> dict | None:
    path = article_path(slug)
    try:
        m = os.path.getmtime(path)
    except OSError:
        return None
    hit = _cache["articles"].get(slug)
    if hit and hit["mtime"] == m:
        return hit
    with open(path) as fh:
        src = fh.read()
    # the view prints the title in its own header, so the article's H1 would
    # be a second copy of it; the lede under it stays.
    body = re.sub(r"\A\s*#\s+[^\n]*\n", "", src)
    rendered = mdlite.render(body, lambda s: "?study=" + s)
    words = len(re.findall(r"[A-Za-z0-9'’-]+", re.sub(r"(?s)```.*?```", "", src)))
    out = {"mtime": m, "source": src, "summary": _summary(src), "words": words,
           "html": rendered["html"], "toc": rendered["toc"],
           "snippets": rendered["snippets"], "checks": rendered["checks"]}
    _cache["articles"][slug] = out
    return out


def has_article(slug: str) -> bool:
    return os.path.isfile(article_path(slug))


# ------------------------------------------------------------------ listings
def listing(progress=None, bank=None) -> dict:
    """Every topic, ranked, with how far the reader has got."""
    idx = index()
    studied = progress.topics_all() if progress else {}
    solved = set(progress.ids_with(status="solved")) if progress else set()
    out = []
    for t in idx["topics"]:
        a = article(t["slug"])
        ids = t.get("problems") or []
        st = studied.get(t["slug"]) or {}
        out.append({
            "slug": t["slug"], "title": t["title"], "category": t["category"],
            "rank": t["rank"], "count": t["count"], "rare": t["rare"],
            "kind": t.get("kind", "topic"),
            "needs": t["needs"], "near": t["near"], "covers": t.get("covers") or [],
            "summary": (a or {}).get("summary", ""),
            "words": (a or {}).get("words", 0),
            "hasArticle": a is not None,
            "solved": sum(1 for i in ids if i in solved),
            "status": st.get("status"),
        })
    cats = []
    for t in out:
        if t["category"] not in cats:
            cats.append(t["category"])
    return {"topics": out, "categories": cats, "problems": idx.get("problems", 0),
            "withArticles": sum(1 for t in out if t["hasArticle"])}


def detail(slug: str, bank=None, progress=None, queue_limit: int = 400) -> dict | None:
    idx = index()
    t = idx["bySlug"].get(slug)
    if not t:
        return None
    a = article(slug)
    ids = (t.get("problems") or [])[:queue_limit]
    queue = []
    if ids and bank is not None:
        rows = {r["id"]: r for r in bank.query({"ids": ids}, sort="default",
                                               limit=len(ids)).get("items", [])}
        prog = {}
        if progress is not None:
            prog = {i: progress.get(i) for i in ids if i in rows}
        try:
            import solutions
            verified = solutions.verified_ids()
        except Exception:
            verified = set()
        for i in ids:
            r = rows.get(i)
            if not r:
                continue
            p = prog.get(i) or {}
            queue.append({"id": i, "title": r["title"], "difficulty": r["difficulty"],
                          "company": r["company"], "seenCount": r["seenCount"],
                          "status": p.get("status"), "hasSolution": i in verified})
    st = progress.topic_get(slug) if progress is not None else {}
    related = []
    for s in list(t["needs"]) + list(t["near"]):
        o = idx["bySlug"].get(s)
        if o and all(r["slug"] != s for r in related):
            related.append({"slug": s, "title": o["title"], "count": o["count"],
                            "kind": "prerequisite" if s in t["needs"] else "next",
                            "hasArticle": has_article(s)})
    return {
        "slug": slug, "title": t["title"], "category": t["category"],
        "rank": t["rank"], "count": t["count"], "rare": t["rare"],
        "kind": t.get("kind", "topic"), "covers": t.get("covers") or [],
        "related": related,
        "article": None if a is None else {
            "html": a["html"], "toc": a["toc"], "words": a["words"],
            "checks": a["checks"], "summary": a["summary"],
            "snippets": [{"lang": s["lang"], "run": s["run"], "code": s["code"]}
                         for s in a["snippets"]],
        },
        "queue": queue, "queueTotal": t["count"],
        "study": st,
    }
